#服务配置
server:
  port: 8086
  address: localhost
  servlet:
    context-path: /extend
#spring配置
spring:
  #1.应用配置
  application:
    name: blog-extend #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hk_blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

# spring cloud 服务配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos服务ip
      config:
        server-addr: 127.0.0.1:8848
  # redis 服务
  redis:
    host: 127.0.0.1
    port: 6379
    #password: root
    timeout: 3000


# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

jwt:
  config:
    salt: HK-Blog
    expireTime: 10800000 # 3小时失效
